@startuml

class Animal {

	- id : int
	- name : String
	- age : int

    -- Contructors --
    + Animal()
    
    -- Public methods --
    + printAnimalName() : void
	+ getYearOfBirth(currentYear : int) : int
}

@enduml
