@startuml

note top of Animal: Class
class Animal {
- id : int
- name : String
- age : int

+ Animal() : ctor
==================

+ printAnimalName() : void
+ getYearOfBirth(currentYear : int) : int
}

note top of Shape: Extends
class Shape
class Circle 
Shape <|-- Circle : extends

note top of OrderDao: Implements
interface OrderDao
class OrderDaoImpl
OrderDao <|.. OrderDaoImpl : Implements

note top of Person: Composition
class Person
class Heart 
class Legs
class Hands

Person *-- Heart
Person *-- Legs
Person *-- Hands

@enduml
